/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import Laya.Skeleton;
	import ui.Views.CheckInDay6RenderObjUI;
	import ui.Views.CheckInDay7RrwardRenderObjUI;
	import ui.Views.Base.CloseBtnObjUI;
	import ui.Views.SkillUpgradeRenderObjUI;
	import ui.Views.SkinRenderObjUI;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 576;
		public static var height:int = 1024;
		public static var scaleMode:String = "fixedwidth";
		public static var screenMode:String = "vertical";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "Views/Base/Init.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("Laya.Skeleton",Skeleton);
			reg("ui.Views.CheckInDay6RenderObjUI",CheckInDay6RenderObjUI);
			reg("ui.Views.CheckInDay7RrwardRenderObjUI",CheckInDay7RrwardRenderObjUI);
			reg("ui.Views.Base.CloseBtnObjUI",CloseBtnObjUI);
			reg("ui.Views.SkillUpgradeRenderObjUI",SkillUpgradeRenderObjUI);
			reg("ui.Views.SkinRenderObjUI",SkinRenderObjUI);
		}
		GameConfig.init();
	}
}