/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AnimationObj from "./script/Game/Views/Base/AnimationObj"
import CloseBtnObj from "./script/Game/Views/Base/CloseBtnObj"
import Init from "./script/Game/Views/Base/Init"
import RedDotObj from "./script/Game/Views/Base/RedDotObj"
import SkillUpgradeObj from "./script/Game/Views/SkillUpgradeObj"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=576;
    static height:number=1024;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Views/Base/Init.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Game/Views/Base/AnimationObj.ts",AnimationObj);
        reg("script/Game/Views/Base/CloseBtnObj.ts",CloseBtnObj);
        reg("script/Game/Views/Base/Init.ts",Init);
        reg("script/Game/Views/Base/RedDotObj.ts",RedDotObj);
        reg("script/Game/Views/SkillUpgradeObj.ts",SkillUpgradeObj);
    }
}
GameConfig.init();