/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Game from "./view/Game"
import Load from "./view/Load"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=576;
    static height:number=1024;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/Load.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("view/Game.ts",Game);
        reg("view/Load.ts",Load);
    }
}
GameConfig.init();