/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class GameUI extends View {
		public Box_YaoGan:Laya.Box;
		public Box_YG:Laya.Box;
		public Img_YaoGanDi:Laya.Image;
		public Img_YaoGan:Laya.Image;
		public ScreenShotBox:Laya.Box;
		public ScreenShot:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Game");
        }
    }
    REG("ui.test.GameUI",GameUI);
    export class LoadUI extends View {
		public bg:Laya.Box;
		public loadingbg:Laya.Image;
		public Middle:Laya.Box;
		public gamelogo:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Load");
        }
    }
    REG("ui.test.LoadUI",LoadUI);
}