/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class LoadUI extends Dialog {
		public bg:Laya.Box;
		public loadingbg:Laya.Image;
		public Middle:Laya.Box;
		public gamelogo:Laya.Image;
		public stdio:Laya.Skeleton;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Load");
        }
    }
    REG("ui.test.LoadUI",LoadUI);
}