/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.Views {
    export class ADGetRewardUI extends View {
		public background:Laya.Image;
		public tattle:Laya.Image;
		public tattleWard:Laya.Image;
		public rewardBigPic:Laya.Image;
		public btnNextTime:Laya.Image;
		public btnADGet:any;
		public imgBtnWord:Laya.Image;
		public rewardIcon:Laya.Image;
		public rewardNum:Laya.Label;
		public btnADNative:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/ADGetReward");
        }
    }
    REG("ui.Views.ADGetRewardUI",ADGetRewardUI);
    export class BeRewardedUI extends View {
		public background:Laya.Image;
		public rewardBigPic:Laya.Image;
		public btnADGet:any;
		public imgBtnWordThree:Laya.Image;
		public imgBtnDirectWord:Laya.Image;
		public btnDirect:Laya.Image;
		public boxNum:Laya.Box;
		public rewardIcon:Laya.Image;
		public rewardNum:Laya.Label;
		public btnADNative:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/BeRewarded");
        }
    }
    REG("ui.Views.BeRewardedUI",BeRewardedUI);
    export class CheckInUI extends View {
		public aniOpen:Laya.FrameAnimation;
		public aniDay7:Laya.FrameAnimation;
		public background:Laya.Image;
		public content:Laya.Box;
		public tattle:Laya.Image;
		public listDay6:Laya.List;
		public day7Box:Laya.Box;
		public imgPainting:Laya.Image;
		public listDay7Reward:Laya.List;
		public dayNum:Laya.Label;
		public lbAlready:Laya.Label;
		public btnCheck:any;
		public btnADGet:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/CheckIn");
        }
    }
    REG("ui.Views.CheckInUI",CheckInUI);
    export class CheckInDay6RenderObjUI extends View {
		public aniHint:Laya.FrameAnimation;
		public board:Laya.Image;
		public dayNum:Laya.Image;
		public icon:Laya.Image;
		public alreadyPic:Laya.Image;
		public rewardNum:Laya.Label;
		public imgMask:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/CheckInDay6RenderObj");
        }
    }
    REG("ui.Views.CheckInDay6RenderObjUI",CheckInDay6RenderObjUI);
    export class CheckInDay7RrwardRenderObjUI extends View {
		public icon:Laya.Image;
		public rewardNum:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/CheckInDay7RrwardRenderObj");
        }
    }
    REG("ui.Views.CheckInDay7RrwardRenderObjUI",CheckInDay7RrwardRenderObjUI);
    export class DefeatedUI extends View {
		public background:Laya.Image;
		public lbLvNum:Laya.Label;
		public btnADGet:any;
		public btnAgain:Laya.Image;
		public rewardBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Defeated");
        }
    }
    REG("ui.Views.DefeatedUI",DefeatedUI);
    export class EndLessSettleUI extends View {
		public background:Laya.Image;
		public lbMileage:Laya.Label;
		public tattle:Laya.Image;
		public rewardIcon:Laya.Image;
		public lbRewardNum:Laya.Label;
		public btnDirect:Laya.Image;
		public btnADGet:any;
		public btnADNative:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/EndLessSettle");
        }
    }
    REG("ui.Views.EndLessSettleUI",EndLessSettleUI);
    export class LevelsUI extends View {
		public aniRefuel1:Laya.FrameAnimation;
		public aniRefuel2:Laya.FrameAnimation;
		public aniKey1:Laya.FrameAnimation;
		public aniKey2:Laya.FrameAnimation;
		public aniKey3:Laya.FrameAnimation;
		public aniBeAttacked:Laya.FrameAnimation;
		public aniContinuousNum:Laya.FrameAnimation;
		public boxKey:Laya.Box;
		public key1:Laya.Image;
		public key2:Laya.Image;
		public key3:Laya.Image;
		public boxLv:Laya.Box;
		public levelProgress:Laya.Image;
		public lbCurLevel:Laya.Label;
		public lbBubblesNum:Laya.Label;
		public boxRoleData:Laya.Box;
		public lbContinuousNum:Laya.Label;
		public imgBeAttacked:Laya.Image;
		public boxEndless:Laya.Box;
		public lbMileage:Laya.Label;
		public boxOpenChest:Laya.Box;
		public imgOpenChestPro:Laya.Image;
		public boxStorage:Laya.Box;
		public imgRainbowEnergy:Laya.Image;
		public imgDiamond:Laya.Image;
		public lbDiamondNum:Laya.Label;
		public btnReturn:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Levels");
        }
    }
    REG("ui.Views.LevelsUI",LevelsUI);
    export class LotteryUI extends View {
		public content:Laya.Box;
		public lbOpenAll:Laya.Label;
		public boxKey:Laya.Box;
		public key1:Laya.Image;
		public key2:Laya.Image;
		public key3:Laya.Image;
		public boxTitle:Laya.Box;
		public imgBestRewardPic:Laya.Image;
		public lbBsetRewardNum:Laya.Label;
		public btnADGet:any;
		public chestBox:Laya.Box;
		public btnReturn:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Lottery");
        }
    }
    REG("ui.Views.LotteryUI",LotteryUI);
    export class LotteryRenderObjUI extends View {
		public ani1:Laya.FrameAnimation;
		public imgRewardIcon:Laya.Image;
		public chestIcon:Laya.Image;
		public imgAd:Laya.Image;
		public lbNum:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/LotteryRenderObj");
        }
    }
    REG("ui.Views.LotteryRenderObjUI",LotteryRenderObjUI);
    export class LuckyWheelUI extends View {
		public background:Laya.Image;
		public tattle:Laya.Image;
		public btnLater:Laya.Image;
		public rewardContent:Laya.Image;
		public btnADNative:any;
		public btnADGet:any;
		public imgWordFree:Laya.Image;
		public imgWordTurn:Laya.Image;
		public pointer:Laya.Image;
		public lbNum:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/LuckyWheel");
        }
    }
    REG("ui.Views.LuckyWheelUI",LuckyWheelUI);
    export class LuckyWheelRenderObjUI extends View {
		public icon:Laya.Image;
		public num:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/LuckyWheelRenderObj");
        }
    }
    REG("ui.Views.LuckyWheelRenderObjUI",LuckyWheelRenderObjUI);
    export class PropTryUI extends View {
		public ani1:Laya.FrameAnimation;
		public background:Laya.Image;
		public imgRewardPic:Laya.Image;
		public btnADGet:any;
		public btnDirect:Laya.Image;
		public btnADNative:any;
		public lbDescribe:Laya.Label;
		public tattle:Laya.Image;
		public tattleWard:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/PropTry");
        }
    }
    REG("ui.Views.PropTryUI",PropTryUI);
    export class ResurgenceUI extends View {
		public background:Laya.Image;
		public btnAbandon:Laya.Label;
		public btnADNative:any;
		public btnADGet:any;
		public tattle:Laya.Image;
		public ftcCountDown:Laya.FontClip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Resurgence");
        }
    }
    REG("ui.Views.ResurgenceUI",ResurgenceUI);
    export class SkillUpgradeObjUI extends View {
		public show:Laya.FrameAnimation;
		public list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/SkillUpgradeObj");
        }
    }
    REG("ui.Views.SkillUpgradeObjUI",SkillUpgradeObjUI);
    export class SkillUpgradeRenderObjUI extends View {
		public imgBoard:Laya.Image;
		public imgSkillIcon:Laya.Image;
		public imgName:Laya.Image;
		public btnUpgrade:Laya.Box;
		public ImgResBoard:Laya.Image;
		public imgResIcon:Laya.Image;
		public ImgMaxLv:Laya.Image;
		public lbConsume:Laya.Label;
		public lbLevel:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/SkillUpgradeRenderObj");
        }
    }
    REG("ui.Views.SkillUpgradeRenderObjUI",SkillUpgradeRenderObjUI);
    export class SkinUI extends View {
		public aniOpen:Laya.FrameAnimation;
		public boxTap:Laya.Box;
		public imgTap0:Laya.Image;
		public imgTap1:Laya.Image;
		public imgTap2:Laya.Image;
		public btnReturn:Laya.Image;
		public boxContent:Laya.Box;
		public list:Laya.List;
		public btnGet:Laya.Image;
		public boxFree:Laya.Box;
		public price:Laya.Label;
		public boxCheckIn:Laya.Box;
		public boxLotteryChest:Laya.Box;
		public boxAD:Laya.Box;
		public boxADNum:Laya.Label;
		public boxGold:Laya.Box;
		public boxGoldNum:Laya.Label;
		public boxLuckyWheel:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Skin");
        }
    }
    REG("ui.Views.SkinUI",SkinUI);
    export class SkinRenderObjUI extends View {
		public aniBuy:Laya.FrameAnimation;
		public imgAniBoard:Laya.Image;
		public imgBoard:Laya.Image;
		public imgIcon:Laya.Image;
		public imgLock:Laya.Image;
		public lbDescribe:Laya.Label;
		public imgDesIcon:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/SkinRenderObj");
        }
    }
    REG("ui.Views.SkinRenderObjUI",SkinRenderObjUI);
    export class SkinTryUI extends View {
		public background:Laya.Image;
		public btnADGet:Laya.Image;
		public btnDirect:Laya.Image;
		public btnADNative:any;
		public tattle:Laya.Image;
		public tattleWard:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/SkinTry");
        }
    }
    REG("ui.Views.SkinTryUI",SkinTryUI);
    export class SpecialAwardsUI extends View {
		public ani1:Laya.FrameAnimation;
		public background:Laya.Image;
		public imgReward:Laya.Image;
		public boxEndlessInto:Laya.Box;
		public btnEndlessInto:Laya.Image;
		public lbHintWord:Laya.Label;
		public boxSkinTry:Laya.Box;
		public btnSkinTry:Laya.Image;
		public boxCurrency:Laya.Box;
		public btnCurrency3M:any;
		public imgBtnWordThree:Laya.Image;
		public boxNum:Laya.Box;
		public rewardIcon:Laya.Image;
		public lbCurrencyNum:Laya.Label;
		public boxSkin:Laya.Box;
		public btnSkin:any;
		public imgBtnDirectWord:Laya.Image;
		public boxLuckyWheelAgain:Laya.Box;
		public btnLuckyWheelAgain:any;
		public btnNextTime:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/SpecialAwards");
        }
    }
    REG("ui.Views.SpecialAwardsUI",SpecialAwardsUI);
    export class VictoryUI extends View {
		public ani1:Laya.FrameAnimation;
		public background:Laya.Image;
		public rewardBox:Laya.Box;
		public tattle:Laya.Image;
		public lbLvNum:Laya.Label;
		public imgPointerMultiple:Laya.Image;
		public btnDirect:Laya.Image;
		public btnADGet:any;
		public lbRewardNum:Laya.Label;
		public btnADNative:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Victory");
        }
    }
    REG("ui.Views.VictoryUI",VictoryUI);
}
export module ui.Views.Base {
    export class CloseBtnObjUI extends View {
		public btnClose:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/CloseBtnObj");
        }
    }
    REG("ui.Views.Base.CloseBtnObjUI",CloseBtnObjUI);
    export class DialogCommonUI extends View {
		public open_popup:Laya.FrameAnimation;
		public open_popupRotate:Laya.FrameAnimation;
		public close_shrink:Laya.FrameAnimation;
		public background:Laya.Image;
		public content:Laya.Box;
		public Board:Laya.Image;
		public ViewBox:Laya.Box;
		public BtnClose:Laya.Image;
		public Tattle:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/DialogCommon");
        }
    }
    REG("ui.Views.Base.DialogCommonUI",DialogCommonUI);
    export class DialogHintUI extends View {
		public background:Laya.Image;
		public Single:Laya.Box;
		public board:Laya.Image;
		public title:Laya.Label;
		public btnClose:Laya.Image;
		public btnConfirm:Laya.Image;
		public describe:Laya.Label;
		public content_Check:Laya.Box;
		public checkBox:Laya.Image;
		public checkPic:Laya.Image;
		public Double:Laya.Box;
		public boxTitle:Laya.Image;
		public btnCloseDouble:Laya.Image;
		public btnCancelDouble:Laya.Image;
		public btnConfirmDouble:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/DialogHint");
        }
    }
    REG("ui.Views.Base.DialogHintUI",DialogHintUI);
    export class DiamondObjUI extends View {
		public baord:Laya.Image;
		public icon:Laya.Image;
		public btnAdd:Laya.Image;
		public num:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/DiamondObj");
        }
    }
    REG("ui.Views.Base.DiamondObjUI",DiamondObjUI);
    export class DiamondSingleObjUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/DiamondSingleObj");
        }
    }
    REG("ui.Views.Base.DiamondSingleObjUI",DiamondSingleObjUI);
    export class FloatFontArtObjUI extends View {
		public ani1:Laya.FrameAnimation;
		public ani2:Laya.FrameAnimation;
		public ani3:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public lbContent:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/FloatFontArtObj");
        }
    }
    REG("ui.Views.Base.FloatFontArtObjUI",FloatFontArtObjUI);
    export class FloatFontSystemObjUI extends View {
		public ani1:Laya.FrameAnimation;
		public imgIcon:Laya.Image;
		public lbContent:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/FloatFontSystemObj");
        }
    }
    REG("ui.Views.Base.FloatFontSystemObjUI",FloatFontSystemObjUI);
    export class GameManagerUI extends View {
		public plValueView:Laya.Panel;
		public btnClose:Laya.Image;
		public btnConfirm:Laya.Image;
		public btnPause:Laya.Image;
		public btnReset:Laya.Image;
		public btnClear:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/GameManager");
        }
    }
    REG("ui.Views.Base.GameManagerUI",GameManagerUI);
    export class GameManagerBtnObjUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/GameManagerBtnObj");
        }
    }
    REG("ui.Views.Base.GameManagerBtnObjUI",GameManagerBtnObjUI);
    export class GameManagerRenderObjUI extends View {
		public lbKey:Laya.Label;
		public txPValue:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/GameManagerRenderObj");
        }
    }
    REG("ui.Views.Base.GameManagerRenderObjUI",GameManagerRenderObjUI);
    export class GoldObjUI extends View {
		public baord:Laya.Image;
		public icon:Laya.Image;
		public btnAdd:Laya.Image;
		public num:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/GoldObj");
        }
    }
    REG("ui.Views.Base.GoldObjUI",GoldObjUI);
    export class GuideUI extends View {
		public aniHint:Laya.FrameAnimation;
		public background:Laya.Image;
		public imgStageClick:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/Guide");
        }
    }
    REG("ui.Views.Base.GuideUI",GuideUI);
    export class InitUI extends View {
		public background:Laya.Image;
		public companyLogoBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/Init");
        }
    }
    REG("ui.Views.Base.InitUI",InitUI);
    export class PreLoadUI extends View {
		public bg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/PreLoad");
        }
    }
    REG("ui.Views.Base.PreLoadUI",PreLoadUI);
    export class PreLoadCutInUI extends View {
		public boxChangeMode:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/PreLoadCutIn");
        }
    }
    REG("ui.Views.Base.PreLoadCutInUI",PreLoadCutInUI);
    export class RedDotObjUI extends View {
		public aniHint:Laya.FrameAnimation;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/RedDotObj");
        }
    }
    REG("ui.Views.Base.RedDotObjUI",RedDotObjUI);
    export class ReturnBtnObjUI extends View {
		public btnReturn:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/ReturnBtnObj");
        }
    }
    REG("ui.Views.Base.ReturnBtnObjUI",ReturnBtnObjUI);
    export class SetUI extends View {
		public background:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/Set");
        }
    }
    REG("ui.Views.Base.SetUI",SetUI);
    export class StaminaObjUI extends View {
		public baord:Laya.Image;
		public icon:Laya.Image;
		public btnAdd:Laya.Image;
		public boxCountHint:Laya.Box;
		public countDown:Laya.Label;
		public num:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/StaminaObj");
        }
    }
    REG("ui.Views.Base.StaminaObjUI",StaminaObjUI);
    export class StartUI extends View {
		public key1Ani:Laya.FrameAnimation;
		public startWord:Laya.FrameAnimation;
		public key2Ani:Laya.FrameAnimation;
		public key3Ani:Laya.FrameAnimation;
		public aniOpen:Laya.FrameAnimation;
		public aniChangeMode:Laya.FrameAnimation;
		public startPic:Laya.Image;
		public btnCheckIn:Laya.Image;
		public btnLottery:Laya.Image;
		public key3:Laya.Image;
		public key2:Laya.Image;
		public key1:Laya.Image;
		public btnLotteryADPic:Laya.Image;
		public btnLuckyWheel:Laya.Image;
		public btnSkin:Laya.Image;
		public btnCutMode:Laya.Image;
		public imgLogo:any;
		public lbEndlessTitle:Laya.Label;
		public boxChangeMode:Laya.Box;
		public lodeSk:Laya.Skeleton;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Views/Base/Start");
        }
    }
    REG("ui.Views.Base.StartUI",StartUI);
}